backend/controllers/RolesController.php
<?php
/**
 * Created by PhpStorm.
 * User: manowartop
 * Date: 09.08.17
 * Time: 15:45
 */

namespace backend\controllers;

use backend\models\Model;
use common\components\rbac\baseController;
use common\components\rbac\models\GroupPermissionForm;
use common\components\rbac\models\RoleEditForm;
use Yii;
use yii\web\NotFoundHttpException;

/**
 * Class RolesController
 * @package backend\controllers
 */
class RolesController extends baseController
{
    /**
     * Список ролей
     *
     * @param null $name
     * @param int $type
     * @return string
     */
    public function actionIndex($name = null, $type = 1)
    {
        $roles = Yii::$app->authManager->getRoles();

        $groupPermissions = Yii::$app->accessControl->getAllGroupPermission();
        if ($name != null) {
            if ($type == 1) {
                $role = Yii::$app->authManager->getRole($name);
                Yii::$app->authManager->remove($role);
                Yii::$app->session->setFlash('danger', 'Роль удалена');
                return $this->redirect(['index', 'roles' => $roles, 'permissions' => $groupPermissions]);
            } else {
                Yii::$app->accessControl->deleteGroupPermission($name);
                Yii::$app->session->setFlash('danger', 'Группа разрешений удалена');
                return $this->redirect(['index', 'roles' => $roles, 'permissions' => $groupPermissions]);
            }
        }
        return $this->render('index', [
            'roles'       => $roles,
            'permissions' => $groupPermissions,
        ]);
    }

    /**
     * Создание/обновление ролей
     *
     * @param null $name
     *
     * @return string|\yii\web\Response
     *
     * @throws \yii\db\Exception
     * @throws \Exception
     */
    public function actionCreateUpdate($name = null)
    {

        if ($name == null) {
            $rbacs = Model::createMultiple(new RoleEditForm());
            if (Model::loadMultiple($rbacs, Yii::$app->request->post()) && Model::validateMultiple($rbacs)) {
                $transaction = Yii::$app->db->beginTransaction();

                if (Yii::$app->accessControl->addRoles($rbacs)) {
                    $transaction->commit();
                    Yii::$app->session->setFlash('success', 'Роль успешно создана');
                    return $this->redirect('index');
                } else {
                    $transaction->rollBack();

                }

            }
            return $this->render('create', [
                'rbacs'    => (empty($rbacs)) ? [new RoleEditForm()] : $rbacs,
                'isCreate' => true
            ]);
        } else {

            $role = Yii::$app->authManager->getRole($name);
            $rbacs = new RoleEditForm(['scenario' => 'update']);
            $rbacs->loadAttributes($role);
            if ($rbacs->load(Yii::$app->request->post())) {
                if (Yii::$app->accessControl->editRole($rbacs->name, $rbacs->description)) {
                    Yii::$app->session->setFlash('success', 'Роль успешно изменена');
                    $this->redirect('index');
                }

            }
            return $this->render('create', [
                'rbacs'    => $rbacs,
                'isCreate' => false
            ]);
        }

    }

    /**
     * Создание/обновление груп разрешений
     *
     * @param null $name
     *
     * @return string|\yii\web\Response
     *
     * @throws \yii\db\Exception
     * @throws \Exception
     */
    public function actionCreateUpdateGroupPermission($name = null)
    {
        if ($name == null) {
            $permissions = Model::createMultiple(new GroupPermissionForm());
            if (Model::loadMultiple($permissions, Yii::$app->request->post()) && Model::validateMultiple($permissions)) {
                $transaction = Yii::$app->db->beginTransaction();

                if (Yii::$app->accessControl->addGroupPermissions($permissions)) {
                    $transaction->commit();
                    Yii::$app->session->setFlash('success', 'Группа разрешений успешно создана');
                    return $this->redirect('index');
                } else {
                    $transaction->rollBack();
                }

            }
            return $this->render('group_create', [
                'permissions' => (empty($permissions)) ? [new GroupPermissionForm()] : $permissions,
                'isCreate'    => true
            ]);
        } else {

            $permission = Yii::$app->accessControl->getGroupPermission($name);

            $form = new GroupPermissionForm();
            $form->systemName = $permission->description;
            if ($form->load(Yii::$app->request->post())) {

                if (Yii::$app->accessControl->addGroupPermission($form->systemName)) {
                    Yii::$app->session->setFlash('success', 'Группа разрешений успешно создана');
                    $this->redirect('index');
                }

            }
            return $this->render('group_create', [
                'permissions' => $form,
                'isCreate'    => false
            ]);
        }
    }

    /**
     * Метод добавления пользователя к групе разрешений
     *
     * @return bool
     *
     * @throws \yii\base\Exception
     */
    public function actionUpdate()
    {

        if (Yii::$app->request->isPost) {
            $data = Yii::$app->request->post();
            if (isset($data['role']) and isset($data['group']) and isset($data['status'])) {

                if ($data['status'] == 1) {
                    Yii::$app->accessControl->addGroupToRole($data['role'], $data['group']);
                    return true;
                }

                if ($data['status'] == 0) {
                    Yii::$app->accessControl->deleteGroupToRole($data['role'], $data['group']);
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * Список роутов группы
     *
     * @param $name
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionRouteList($name)
    {
        $group = Yii::$app->authManager->getPermission($name);
        $list = Yii::$app->authManager->getChildren($name);
        if ($list === null) throw new NotFoundHttpException();

        return $this->render('route-list', ['list' => $list, 'group' => $group]);
    }

    /**
     * Удаление роута из группы
     *
     * @param $name
     * @param $group
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionRemoveRoute($name, $group)
    {
        Yii::$app->accessControl->deleteRouteToGroup($name, $group);
        return $this->actionRouteList($group);
    }
}

backend/views/roles/_form.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use wbraganca\dynamicform\DynamicFormWidget;

/**
 * @var bool $isCreate
 * @var array $rbacs
 * @var \common\components\rbac\models\RoleEditForm $rbacs
 */
?>
<section id="description" class="card">
    <div class="card-header">
        <h4 class="card-title"><?= $this->title ?></h4>
    </div>
    <div class="card-body collapse in">
        <div class="card-block">
            <div class="card-text">

                <?php $form = ActiveForm::begin(['id' => 'dynamic-form']) ?>

                <?= Html::submitButton(($isCreate) ? 'Добавить' : 'Изменить', ['class' => 'btn btn-info']) ?>
                <?php if ($isCreate) { ?>
                <div class="panel-body">
                    <?php DynamicFormWidget::begin([
                        'widgetContainer' => 'dynamicform_wrapper',
                        'widgetBody'      => '.container-items',
                        'widgetItem'      => '.item',
                        'limit'           => 20,
                        'min'             => 1,
                        'insertButton'    => '.add-item',
                        'deleteButton'    => '.remove-item',
                        'model'           => $rbacs[0],
                        'formId'          => 'dynamic-form',
                        'formFields'      => [
                            'w_size',
                            'h_size',
                        ],
                    ]); ?>
                    <div class="container-items">
                        <?php foreach ($rbacs as $i => $item): ?>
                            <div class="item panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title pull-left">Роль</h3>
                                    <div class="pull-right">
                                        <button type="button" class="add-item btn btn-success btn-xs"><i
                                                    class="glyphicon glyphicon-plus"></i></button>
                                        <button type="button" class="remove-item btn btn-danger btn-xs"><i
                                                    class="glyphicon glyphicon-minus"></i></button>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="panel-body">

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <?= $form->field($item, "[{$i}]name")->textInput() ?>
                                        </div>
                                        <div class="col-sm-6">
                                            <?= $form->field($item, "[{$i}]description")->textInput() ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        <?php DynamicFormWidget::end(); ?>
                    </div>
                    <?php } else { ?>
                        <?= $form->field($rbacs, 'name')->textInput(['readonly' => 'readonly']) ?>

                        <?= $form->field($rbacs, 'description')->textInput() ?>
                    <?php } ?>

                    <?php ActiveForm::end() ?>
                </div>
            </div>
        </div>
    </div>
</section>

backend/views/roles/create.php
<?php

/**
 * @var boolean $isCreate
 * @var \common\components\rbac\models\RoleEditForm[] $rbacs
 */

count($rbacs) > 1 ? $this->title = 'Роль - ' . $rbacs->name : $this->title = 'Добавить роли';
$this->params['breadcrumbs'][] = ['label' => 'RBAC', 'url' => ['/roles']];
$this->params['breadcrumbs'][] = $this->title;
echo $this->render('_form', ['rbacs' => $rbacs, 'isCreate' => $isCreate]);
?>

backend/views/roles/group_create.php
<?php

/** @var boolean $isCreate */
$this->title = (!is_array($permissions) && $permissions->systemName != '') ? 'Группа - ' . $permissions->systemName : 'Новая группа разрешений';

$this->params['breadcrumbs'][] = ['label' => 'RBAC', 'url' => ['/roles']];
$this->params['breadcrumbs'][] = $this->title;
echo $this->render('group_form', ['permissions' => $permissions, 'isCreate' => $isCreate]);

backend/views/roles/group_form.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use wbraganca\dynamicform\DynamicFormWidget;

/**
 * @var bool $isCreate
 * @var \common\components\rbac\models\GroupPermissionForm $permissions
 */

?>
<section id="description" class="card">
    <div class="card-header">
        <h4 class="card-title"><?= $this->title ?></h4>
    </div>
    <div class="card-body collapse in">
        <div class="card-block">
            <div class="card-text">

                <?php $form = ActiveForm::begin(['id' => 'dynamic-form']) ?>
                <?= Html::submitButton(($isCreate) ? 'Добавить' : 'Изменить', ['class' => 'btn btn-info']) ?>
                <?php if ($isCreate) { ?>
                <div class="panel-body">
                    <?php DynamicFormWidget::begin([
                        'widgetContainer' => 'dynamicform_wrapper',
                        'widgetBody'      => '.container-items',
                        'widgetItem'      => '.item',
                        'limit'           => 20,
                        'min'             => 1,
                        'insertButton'    => '.add-item',
                        'deleteButton'    => '.remove-item',
                        'model'           => $permissions[0],
                        'formId'          => 'dynamic-form',
                        'formFields'      => [
                            'systemName',
                        ],
                    ]); ?>
                    <div class="container-items">
                        <?php foreach ($permissions as $i => $item): ?>
                            <div class="item panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title pull-left">Группа разрешений</h3>
                                    <div class="pull-right">
                                        <button type="button" class="add-item btn btn-success btn-xs"><i
                                                    class="glyphicon glyphicon-plus"></i></button>
                                        <button type="button" class="remove-item btn btn-danger btn-xs"><i
                                                    class="glyphicon glyphicon-minus"></i></button>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="panel-body">

                                    <div class="row">
                                        <div class="col-md-8 col-md-offset-2">
                                            <?= $form->field($item, "[{$i}]systemName")->textInput() ?>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        <?php DynamicFormWidget::end(); ?>
                    </div>
                    <?php } else { ?>
                        <?= $form->field($permissions, 'systemName')->textInput() ?>

                    <?php } ?>
                    <?php ActiveForm::end() ?>
                </div>
            </div>
        </div>
    </div>
</section>

backend/views/roles/route-list.php
<?php

use yii\helpers\Url;

/**
 * @var array $list
 * @var \common\components\rbac\models\GroupPermissionForm $group
 */

?>
<section id="description" class="card">
    <div class="card-header">
        <h4 class="card-title"><?= $this->title ?></h4>
    </div>
    <div class="card-body collapse in">
        <div class="card-block">
            <div class="card-text">
                <table class="table">
                    <th>Ветка</th>
                    <th>Путь</th>
                    <th></th>
                    <?php
                    foreach ($list as $item) { ?>
                        <tr>
                            <?php $info = Yii::$app->accessControl->unParseRoute($item->name);
                            echo '<td><small>' . $info['branch'] . '</small></td><td>' . $info['rout'] . '</td>'; ?>
                            <td>
                                <a class="btn btn-sm btn-danger btn-flat"
                                   href="<?= Url::to(['/roles/remove-route', 'name' => $item->name, 'group' => $group->name]) ?>">
                                    X </a>
                            </td>
                        </tr>
                    <?php } ?>

                </table>
            </div>
        </div>
    </div>
</section>