backend/controllers/HandbookController.php
<?php
/**
 * Created by PhpStorm.
 * User: manowartop
 * Date: 26.07.17
 * Time: 18:33
 */

namespace backend\controllers;


use backend\models\Model;
use common\components\AjaxValidationTrait;
use common\components\handbook\models\Handbook;
use common\components\handbook\models\HandbookData;
use common\components\handbook\models\HandbookFields;
use common\components\handbook\services\HbService;
use common\components\rbac\baseController;
use Yii;
use yii\base\Module;
use yii\helpers\ArrayHelper;
use yii\web\Response;

/**
 * Class HandbookController
 *
 * @package backend\controllers
 */
class HandbookController extends baseController
{
    use AjaxValidationTrait;

    /**
     * @var HbService
     */
    private $hbService;

    /**
     * HandbookController constructor.
     * @param integer $id
     * @param Module $module
     * @param HbService $hbService
     * @param array $config
     */
    public function __construct($id, Module $module, HbService $hbService, array $config = [])
    {
        $this->hbService = $hbService;
        parent::__construct($id, $module, $config);
    }

    /**
     * Список справочников
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new Handbook(['scenario' => Handbook::SCENARIO_SEARCH]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Создание справочника
     *
     * @return array|string|Response
     */
    public function actionCreate()
    {
        $handbook = new Handbook(['scenario' => Handbook::SCENARIO_CREATE]);

        if ($handbook->load(Yii::$app->request->post())) {

            $additionalFields = Model::createMultiple(HandbookFields::class);
            Model::loadMultiple($additionalFields, Yii::$app->request->post());

            if (($errors = $this->validateModelAndModels($handbook, $additionalFields)) !== null) {
                return $errors;
            }

            if ($this->hbService->createOrEditHandbook($handbook, $additionalFields)) {

                Yii::$app->session->setFlash('success', 'Справочник создан');

                return $this->redirect(['handbook/update', 'id' => $handbook->id]);
            }
        }

        return $this->render('structure_form', [
            'handbook' => $handbook,
            'fields'   => empty($additionalFields) ? [new HandbookFields()] : $additionalFields,
        ]);
    }

    /**
     * Добавление записей справочника
     *
     * @param integer $id
     * @return array|null|string|Response
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $handbook = Handbook::findOneStrictException($id);
        $handbook->scenario = Handbook::SCENARIO_CREATE;
        $data = $handbook->getData();

        if (Yii::$app->request->post('HandbookData')) {

            $oldIDs = ArrayHelper::map($data, 'id', 'id');
            $data = Model::createMultiple(HandbookData::class, $data);
            Model::loadMultiple($data, Yii::$app->request->post());

            if (($errors = $this->validateMultipleModels($data)) !== null) {
                return $errors;
            }

            $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($data, 'id', 'id')));
            HandbookData::deleteAll(['id' => $deletedIDs]);

            if ($this->hbService->addData($data)) {

                Yii::$app->session->setFlash('warning', 'Информация справочника изменена');

                return $this->redirect(['index']);
            }
        }

        return $this->render('_form', [
            'handbook' => $handbook,
            'fields'   => $handbook->getFields(),
            'data'     => empty($data) ? [new HandbookData()] : $data,
        ]);
    }

    /**
     * Изменение структуры справочника
     *
     * @param integer $id
     * @return array|null|string|Response
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionUpdateStructure($id)
    {
        $handbook = Handbook::findOneStrictException($id);
        $handbook->scenario = Handbook::SCENARIO_CREATE;

        if ($handbook->load(Yii::$app->request->post())) {

            $additionalFields = Model::createMultiple(HandbookFields::class);
            Model::loadMultiple($additionalFields, Yii::$app->request->post());

            if (($errors = $this->validateModelAndModels($handbook, $additionalFields)) !== null) {
                return $errors;
            }

            if ($this->hbService->createOrEditHandbook($handbook, $additionalFields)) {

                Yii::$app->session->setFlash('success', 'Структура изменена');

                return $this->redirect(['handbook/update', 'id' => $handbook->id]);
            }
        }

        return $this->render('structure_form', [
            'handbook' => $handbook,
            'fields'   => $handbook->getFields() ? $handbook->getFields() : [new HandbookFields()],
        ]);
    }

    /**
     * Удаление справочника
     *
     * @param integer $id
     * @return Response
     */
    public function actionDelete($id)
    {
        if ($this->hbService->deleteHandbook($id)) {
            Yii::$app->session->setFlash('success', 'Справочник удален');

        } else {
            Yii::$app->session->setFlash('danger', 'Невозможно удалить справочник');
        }

        return $this->redirect('index');
    }
}

backend/views/handbook/_form.php
<?php

use common\components\handbook\models\Handbook;
use common\components\handbook\models\HandbookFields;
use common\components\handbook\TypeHelper;
use kartik\widgets\Select2;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use wbraganca\dynamicform\DynamicFormWidget;

/**
 * @var Handbook $handbook
 * @var HandbookFields[] $fields
 * @var array $data
 */

$this->title = 'Данные справочника';

$js = <<<JS
  $(".dynamicform_wrapper").on('afterInsert',function () {
  var hb_id = $('.hb_id');
        hb_id.find('input:hidden').val(hb_id.data('id'));
    });
JS;

$this->registerJs($js);
?>
<section id="description" class="card">
    <div class="card-header">
        <h4 class="card-title"><?= $this->title ?></h4>
    </div>
    <div class="card-body collapse in">
        <div class="card-block">
            <div class="card-text">

                <?php $form = ActiveForm::begin([
                    'id'                     => 'dynamic-form1',
                    'action'                 => ['update', 'id' => $handbook->id],
                    'enableAjaxValidation'   => true,
                    'enableClientValidation' => false,
                ]) ?>
                <?= Html::submitButton('Сохранить записи', ['class' => 'btn btn-success']) ?>
                <?= Html::a('Изменить структуру справочника', Url::toRoute(['handbook/update-structure', 'id' => $handbook->id]), ['class' => 'btn btn-warning']) ?>
                <div class="panel-body">
                    <?php DynamicFormWidget::begin([
                        'widgetContainer' => 'dynamicform_wrapper',
                        'widgetBody'      => '.container-items',
                        'widgetItem'      => '.item',
                        'limit'           => 5000,
                        'min'             => 1,
                        'insertButton'    => '.add-item',
                        'deleteButton'    => '.remove-item',
                        'model'           => $data[0],
                        'formId'          => 'dynamic-form1',
                        'formFields'      => [
                            'handbook_id',
                            'value',
                            'title',
                            'relation',
                            'additionalFields',
                        ],
                    ]); ?>
                    <div class="container-items">
                        <?php foreach ($data

                        as $i => $item): ?>
                        <div class="item panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title pull-left">Добавить значения справочника</h3>
                                <div class="pull-right">
                                    <button type="button" class="add-item btn btn-success btn-xs"><i
                                                class="glyphicon glyphicon-plus"></i></button>
                                    <button type="button" class="remove-item btn btn-danger btn-xs"><i
                                                class="glyphicon glyphicon-minus"></i></button>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="panel-body">

                                <div class="row">
                                    <div class="hb_id" data-id="<?= $handbook->id ?>">
                                        <?= $form->field($item, "[{$i}]handbook_id")->hiddenInput(['value' => $handbook->id])->label(false) ?>
                                    </div>
                                    <div class="col-sm-6">
                                        <?= $form->field($item, "[{$i}]value")->textInput() ?>
                                    </div>
                                    <div class="col-sm-6">
                                        <?= $form->field($item, "[{$i}]title")->textInput() ?>
                                    </div>
                                    <?php if ($handbook->relation) { ?>
                                        <div class="col-sm-12">
                                            <?=
                                            $form->field($item, "[{$i}]relation")->widget(Select2::class, [
                                                'data'          => Yii::$app->handbook->getDataForRelation($handbook->relation),
                                                'language'      => 'ru',
                                                'options'       => ['placeholder' => 'Значение, от которого зависит данное'],
                                                'pluginOptions' => [
                                                    'allowClear' => true,
                                                ],
                                            ]);
                                            ?>
                                        </div>
                                    <?php }
                                    if (!empty($fields)) { ?>
                                        <div class="col-md-12 well">
                                            <h4 style="text-align: center">Дополнительные поля</h4>
                                            <?php
                                            $countFields = round(12 / (count($fields)));
                                            foreach ($fields as $field):
                                                $fieldType = TypeHelper::getTypes($field->type);
                                                $fieldType = $fieldType[3];
                                                $key = $field['name'];
                                                ?>
                                                <div class="col-sm-<?= $countFields ?>">
                                                    <?= $form->field($item, "[{$i}]additionalFields[$key]")->$fieldType()->label($field->description) ?>
                                                </div>
                                            <?php endforeach; ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                            <?php endforeach;
                            DynamicFormWidget::end();
                            ActiveForm::end(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

backend/views/handbook/index.php
<?php

use common\components\handbook\models\Handbook;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;

/**
 * @var Handbook $searchModel
 * @var \yii\data\ActiveDataProvider $dataProvider
 */

$this->title = 'Справочник';
$this->params['breadcrumbs'][] = $this->title;
?>


<section id="description" class="card">
    <div class="card-header">
        <h4 class="card-title"><?= $this->title ?></h4>
        <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
        <div class="heading-elements">
            <ul class="list-inline mb-0">
                <li><a href="<?= Url::toRoute(['/handbook']) ?>"><i class="icon-android-refresh"></i></a></li>
                <li><a href="<?= Url::toRoute(['handbook/create']) ?>"><i class="icon-android-add-circle"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="card-body collapse in">
        <div class="card-block">
            <div class="card-text">
                <?php Pjax::begin() ?>
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'filterModel'  => $searchModel,
                    'tableOptions' => [
                        'class' => 'table'
                    ],
                    'layout'       => '{items} <div class="box-footer clearfix">{pager}</div>',
                    'pager'        => [
                        'options' => [
                            'class' => 'pagination pagination-sm no-margin pull-right'
                        ],
                    ],
                    'columns'      => [
                        [
                            'class'          => 'yii\grid\SerialColumn',
                            'headerOptions'  => ['class' => 'text-center'],
                            'contentOptions' => ['class' => 'text-center']
                        ],
                        'systemName',
                        'description',
                        [
                            'header'  => 'Создано',
                            'content' => function ($model) {
                                return Yii::$app->formatter->asDatetime($model->created_at, 'dd/MM/Y H:i');
                            },
                        ],
                        [
                            'header'  => 'Обновлено',
                            'content' => function ($model) {
                                return Yii::$app->formatter->asDatetime($model->updated_at, 'dd/MM/Y H:i');
                            },
                        ],
                        [
                            'class'          => 'yii\grid\ActionColumn',
                            'header'         => 'Действия',
                            'headerOptions'  => ['class' => 'text-right'],
                            'contentOptions' => ['class' => 'td-actions text-right'],
                            'template'       => '{update} {clone} {delete}',
                            'buttons'        => [
                                'update' => function ($url) {
                                    return Html::a(
                                        '<i class="material-icons">edit</i>',
                                        $url, ['class' => 'btn btn-success']);
                                },
                                'delete' => function ($url) {
                                    return Html::a(
                                        '<i class="material-icons">close</i>',
                                        $url, [
                                        'class'        => 'btn btn-danger',
                                        'title'        => 'Удалить',
                                        'aria-label'   => 'Удалить',
                                        'data-pjax'    => '0',
                                        'data-confirm' => 'Вы уверены, что хотите удалить справочник?',
                                        'data-method'  => 'post'
                                    ]);
                                },
                            ],
                        ],
                    ],
                ]); ?>
                <?php Pjax::end() ?>
            </div>
        </div>
    </div>
</section>

backend/views/handbook/structure_form.php
<?php

use common\components\handbook\models\Handbook;
use common\components\handbook\models\HandbookFields;
use common\components\handbook\TypeHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use wbraganca\dynamicform\DynamicFormWidget;

/**
 * @var Handbook $handbook
 * @var HandbookFields[] $fields
 */

$this->title = $handbook->isNewRecord ? 'Новый справочник' : 'Обновление структуры справочника';

$action = $handbook->isNewRecord ? ['create'] : ['update-structure', 'id' => $handbook->id];
?>
<section id="description" class="card">
    <div class="card-header">
        <h4 class="card-title"><?= $this->title ?></h4>
    </div>
    <div class="card-body collapse in">
        <div class="card-block">
            <div class="card-text">

                <?php $form = ActiveForm::begin([
                    'id'                     => 'dynamic-form',
                    'action'                 => $action,
                    'enableAjaxValidation'   => true,
                    'enableClientValidation' => false,
                ]) ?>

                <div class="col-md-12 block_on_top">
                    <h4 style="text-align: center">Информация о справочнике</h4>
                    <div class="col-md-4">
                        <?= $form->field($handbook, 'systemName')->textInput() ?>
                    </div>
                    <div class="col-md-4">
                        <?= $form->field($handbook, 'description')->textInput() ?>
                    </div>
                    <div class="col-md-4">
                        <?= $form->field($handbook, 'relation')->dropDownList(Yii::$app->handbook->getHandbooksList(), ['prompt' => 'Справочник, от которого зависит данный']) ?>
                    </div>
                    <div class="col-md-12">
                        <?= Html::submitButton($handbook->isNewRecord ? 'Сохранить' : 'Изменить', ['class' => 'btn btn-info']) ?>
                        <?php if (!$handbook->isNewRecord) { ?>
                            <a href="<?= Url::toRoute(['handbook/update', 'id' => $handbook->id]) ?>"
                               class="btn btn-danger"> Перейти к данным </a>
                        <?php } ?>
                        <button class="btn btn-warning add_field pull-right"
                                data-state="<?= $handbook->isNewRecord && count($fields) < 2 ? 1 : 2 ?>">Дополнительные
                            поля
                        </button>
                    </div>
                </div>
                <div class="col-md-12 block_on_top <?= $handbook->isNewRecord && count($fields) < 2 ? 'hidden' : '' ?> additional_fields">
                    <h4 style="text-align: center">Добавить поля к справочнику</h4>

                    <div class="panel-body">
                        <?php DynamicFormWidget::begin([
                            'id'              => 'fields_is',
                            'widgetContainer' => 'dynamicform_wrapper',
                            'widgetBody'      => '.container-items',
                            'widgetItem'      => '.item',
                            'limit'           => 999,
                            'min'             => 1,
                            'insertButton'    => '.add-item',
                            'deleteButton'    => '.remove-item',
                            'model'           => $fields[0],
                            'formId'          => 'dynamic-form',
                            'formFields'      => [
                                'name',
                                'description',
                                'type',
                                'notNull',
                            ],
                        ]); ?>

                        <div class="container-items">
                            <?php foreach ($fields as $i => $item): ?>
                                <div class="item panel panel-default">
                                    <div class="panel-heading">
                                        <h3 class="panel-title pull-left">Добавить поля</h3>
                                        <div class="pull-right">
                                            <button type="button" class="add-item btn btn-success btn-xs"><i
                                                        class="glyphicon glyphicon-plus"></i></button>
                                            <button type="button" class="remove-item btn btn-danger btn-xs"><i
                                                        class="glyphicon glyphicon-minus"></i></button>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-sm-3">
                                                <?= $form->field($item, "[{$i}]name")->textInput() ?>
                                            </div>
                                            <div class="col-sm-3">
                                                <?= $form->field($item, "[{$i}]description")->textInput() ?>
                                            </div>
                                            <div class="col-sm-3">
                                                <?= $form->field($item, "[{$i}]type")->dropDownList(TypeHelper::getTitleTypes(), ['prompt' => '--Тип поля--']) ?>
                                            </div>
                                            <div class="col-sm-3">
                                                <?= $form->field($item, "[{$i}]notNull")->checkbox() ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                            <?php DynamicFormWidget::end(); ?>
                        </div>
                    </div>
                    <?php ActiveForm::end() ?>
                </div>
            </div>
        </div>
</section>